# _config.yml
title: "مكتبة ناصر ابن داوود"
description: "مكتبة رقمية شاملة للدراسات القرآنية"
baseurl: ""
url: "https://nasserhabitat.github.io/nasser-books"

# تعطيل معالجة Jekyll للملفات الثابتة
include: ['.xml', '.txt', '.html']
exclude: ['_site', 'Gemfile', 'Gemfile.lock']

# لا تستخدم أي theme
theme: null
plugins: []
