# _config.yml
include:
  - ".xml"
  - ".txt"

plugins:
  - jekyll-sitemap

# إعدادات المحتوى
defaults:
  - scope:
      path: "*.xml"
    values:
      layout: null
      sitemap: true
  - scope:
      path: "*.txt"
    values:
      layout: null
